### ISSUE TITLE
Regarding dolby

### ISSUE THREAD

**Issue by sureshfizzy** [someone5678/device_xiaomi_sweet#2]
Hi can I get ur telegram I'd have some doubts.

**Comment by someone5678** [comment]
> Hi can I get ur telegram I'd have some doubts.

https://gitlab.com/someone5678/vendor_dolby

I wrote down everything I did in my dolby repo.
Please check the description!

**Comment by sureshfizzy** [comment]
I went through but facing some errors should I import blobs from proprietary-files.txt inside the device tree. My device code is sweet (Redmi note 10 pro ).
