### ISSUE TITLE
Framework

### ISSUE THREAD

**Issue by sureshfizzy** [someone5678/device_xiaomi_sweet#3]
Can you send this file DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE += $(COMMON_PATH)/vendor_framework_compatibility_matrix.xml

I'm not having it

**Comment by someone5678** [comment]
> Can you send this file DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE += $(COMMON_PATH)/vendor_framework_compatibility_matrix.xml
> 
> I'm not having it

It's from PE's device_qcom_common repo which is fork of AOSPA's
https://github.com/PixelExperience-Devices/device_qcom_common

**Comment by someone5678** [comment]
> Can you send this file DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE += $(COMMON_PATH)/vendor_framework_compatibility_matrix.xml
> 
> I'm not having it

By the way, I forgot to let you know my telegram account name
@someone5678_1375

**Comment by sureshfizzy** [comment]
Thanks !!
